### ISSUE TITLE
Support mat-icon within the nav

### ISSUE THREAD

**Issue by adamkasztenny** [michaelbull/material-bottom-nav#3]
It would be nice if `<mat-icon>`s could be used instead of `<svg>`s:

```html
<nav class="bottom-nav">
  <a class="bottom-nav__action" href="#">
    <mat-icon class="bottom-nav__icon">all_inbox</mat-icon>
    <span class="bottom-nav__label">Recents</span>
  </a>

  <a class="bottom-nav__action bottom-nav__action--active" href="#">
    <mat-icon class="bottom-nav__icon">copyright</mat-icon>
    <span class="bottom-nav__label">Favorites</span>
  </a>

  <a class="bottom-nav__action" href="#">
    <mat-icon class="bottom-nav__icon">backup</mat-icon>
    <span class="bottom-nav__label">Nearby</span>
  </a>
</nav>
```

The spacing is off for me if I try this:

![image](https://user-images.githubusercontent.com/12041666/51351926-288a5f00-1a7a-11e9-8c54-d2b5c53ca564.png)

Angular version: 6.1.2
Material version: 6.4.5
material-bottom-nav version: 1.0.6

**Comment by michaelbull** [comment]
You can just apply your own style rules to your own class and apply it to the "mat-icon" element in your example.

**Comment by adamkasztenny** [comment]
Thanks, I'll give that a shot.

**Comment by michaelbull** [comment]
You'll need to emulate these two style rules as they're both specific for svg icons:

1. https://github.com/michaelbull/material-bottom-nav/blob/master/bottom-nav.scss#L103
2. https://github.com/michaelbull/material-bottom-nav/blob/master/bottom-nav.scss#L130

But that's about it.

**Comment by adamkasztenny** [comment]
I needed to remove the `mat-icon` class on `mat-icon` elements to fix the spacing. After that, leaving `bottom-nav__icon` on `mat-icon` works fine.

**Comment by michaelbull** [comment]
Great, I guess the `mat-icon` class had some conflicting style rules that were taking precedence over `bottom-nav__icon`.
