### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by adamkasztenny** [michaelbull/material-bottom-nav#4]
I tried [the demo link in the README](https://michaelbull.github.io/material-bottom-nav/) in Firefox and Chrome and I don't think it works. Clicking any of the menu items doesn't do anything.

**Comment by michaelbull** [comment]
If you look at their anchor tags, they simply link to "#" - they aren't meant to go anywhere as it's purely a demo. The only working links are the one in the page content, e.g. the link to https://michaelbull.github.io/material-bottom-nav/labels-hide.html

**Comment by adamkasztenny** [comment]
Okey dokes, thanks.
